### ISSUE TITLE
마이페이지 UI 구현

### ISSUE THREAD

**Issue by yyoonngg** [KAU-2024-Sanhak/sanhak#10]
### Description
마이페이지 UI 구현

### TODO
1. [x] **마이페이지 상단 Profile**  
    - 사용자 프로필 이미지, 이름 표시
    - 사용자가 그동안 배운 스킬 뱃지들 표시

2. [x] **마이페이지 하단 Custom Roadmap**  
    - 사용자가 만들어둔 커스텀 로드맵 리스트 표시
    - 로드맵 구현
    - 편집모드 구현
      - 드래그로 스킬노드의 위치를 변경 가능

3. [x] **사이드 Detail Description Bar**  
    - 학습 스킬 세부 설명 표시  
    - 목차 표시

### Resources
- 작업 예상 소요 시간: 3 days

**Comment by jyc0011** [comment]
👍
